name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
            
      # Build frontend
      - name: Install and build frontend
        run: |
          cd front-end
          npm install vite --no-save
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env
          npm install
          npm run build
          
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_PRIVATE_KEY }}" > ~/.ssh/lightsail.pem
          chmod 600 ~/.ssh/lightsail.pem
          
      - name: Add host key to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
            
      - name: Upload files to server
        run: |  
          # Upload frontend dist folder (built files)
          scp -i ~/.ssh/lightsail.pem -r front-end/dist front-end/package.json ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}}:/opt/bitnami/projects/coinpurse/front-end/
  
          # Upload backend files
          scp -i ~/.ssh/lightsail.pem -r back-end/server.js back-end/package.json back-end/ecosystem.config.js back-end/src ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}}:/opt/bitnami/projects/coinpurse/back-end
           
          # Connect to server and install dependencies
          ssh -i ~/.ssh/lightsail.pem ${{secrets.SERVER_USER}}@${{secrets.SERVER_HOST}} << 'EOF'
            # Navigate to backend directory
            cd /opt/bitnami/projects/coinpurse/back-end

            # Stop pm2 processes
            npm run stop
             
            # Install dependencies
            echo "Installing backend dependencies..."
            rm -rf node_modules package-lock.json
            npm install --production
  
            # Navigate to frontend directory
            cd ../front-end
            echo "Installing frontend dependencies..."
            rm -rf node_modules package-lock.json
            npm install --production
  
            # Start pm2 processes
            cd ../back-end
            echo "Starting backend..."
            npm run start
          EOF
          
