name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # Backend build
      - name: Install Backend Dependencies
        run: |
          cd back-end
          npm ci

      # Frontend build
      - name: Install Frontend Dependencies
        run: |
          cd front-end
          npm ci
      
      - name: Build Frontend
        run: |
          cd front-end
          npm run build
      
      # Create a deployment package
      - name: Create deployment package
        run: |
          mkdir -p deployment
          cp -r back-end deployment/
          mkdir -p deployment/back-end/public
          cp -r front-end/dist/* deployment/back-end/public/
          cp package.json deployment/ || echo "No root package.json"
          
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_PRIVATE_KEY }}" > ~/.ssh/lightsail.pem
          chmod 600 ~/.ssh/lightsail.pem
          
      - name: Add host key to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to Lightsail
        run: |
          # Compress deployment package
          tar -czf deployment.tar.gz -C deployment .
          
          # Deploy files to server
          scp -i ~/.ssh/lightsail.pem deployment.tar.gz ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/tmp/
          
          # Extract and setup on server
          ssh -i ~/.ssh/lightsail.pem ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            # Stop existing service if needed
            pm2 stop coinpurse-api || true
            
            # Clear deployment directory
            rm -rf /opt/coinpurse
            mkdir -p /opt/coinpurse
            
            # Extract new deployment
            tar -xzf /tmp/deployment.tar.gz -C /opt/coinpurse
            
            # Install dependencies
            cd /opt/coinpurse/back-end
            npm ci --production
            
            # Configure environment variables
            cp /opt/env-files/coinpurse/.env .
            
            # Start the application with PM2
            pm2 start server.js --name coinpurse-api
            
            # Clean up
            rm /tmp/deployment.tar.gz
          EOF

      - name: Cleanup
        run: rm -rf ~/.ssh/lightsail.pem 